CREATE USER IF NOT EXISTS SUNDAY_MANAGER_ADMIN PASSWORD 'SUNDAY_MANAGER_ADMIN';

CREATE SCHEMA IF NOT EXISTS SUNDAY_MANAGER AUTHORIZATION SUNDAY_MANAGER_ADMIN;

GRANT ALL ON SCHEMA SUNDAY_MANAGER TO SUNDAY_MANAGER_ADMIN;